# -*- coding: utf-8 -*-
"""titanic_prod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVuAgD0oh1e6X514uZpzGlnDhavwnfh4
"""

pip freeze > requirements.txt

from sklearn.preprocessing import PowerTransformer
from sklearn.pipeline import Pipeline
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import PowerTransformer, StandardScaler , OneHotEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score
)
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier


df = pd.read_csv("titanic.csv")
df['FamilySize'] = df['sibsp'] + df['parch'] + 1
df['IsAlone'] = (df['FamilySize'] == 1).astype(int)
df['Title'] = df['name'].str.extract(r' ([A-Za-z]+)\.', expand=False)

df['Title'] = df['Title'].replace(
    ['Lady','Countess','Capt','Col','Don','Dr','Major','Rev','Sir','Jonkheer','Dona'],
    'Rare'
)
df['Title'] = df['Title'].replace({'Mlle':'Miss','Ms':'Miss','Mme':'Mrs'})

num_cols = ['age','fare','FamilySize']
cat_cols = ['pclass','sex','embarked','sibsp','parch','Title','IsAlone']
x = df[num_cols + cat_cols]
y = df['survived']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
num_preprocessing = Pipeline([
    ('imputer',SimpleImputer(strategy='median')),#handled the missing data
    ('power', PowerTransformer(method='yeo-johnson')),#handled skewness
    ('standard', StandardScaler()) #Same Scale for each feature
])
cat_preprocessing = Pipeline([
     ('imputer',SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))#encoding
])

preprocessor  = ColumnTransformer([
    ('num', num_preprocessing, num_cols),
    ('cat', cat_preprocessing, cat_cols)
])

pipeline = Pipeline([
    ('preprocess', preprocessor),
    ('classifier',   DecisionTreeClassifier(max_depth=10,
                                            min_samples_leaf=10,
                                           min_samples_split= 25
                                            ,random_state=42))    # Decision Tree classifier with controlled depth and leaf size to reduce overfitting
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)
y_proba = pipeline.predict_proba(x_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))# Overall fraction of correctly predicted samples
print("AUC:", roc_auc_score(y_test, y_proba)) # Measures ability to rank positive samples higher than negative ones (useful for imbalanced data)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

import joblib

joblib.dump(pipeline, 'titanic_pipeline.pkl')

loaded_pipeline = joblib.load('titanic_pipeline.pkl')


sample_data = pd.DataFrame({
    'age': [22, 35],
    'fare': [7.25, 71.83],
    'FamilySize': [1, 3],
    'pclass': [3, 1],
    'sex': ['male', 'female'],
    'embarked': ['S', 'C'],
    'sibsp': [0, 1],
    'parch': [0, 2],
    'Title': ['Mr', 'Mrs'],
    'IsAlone': [1, 0]
})

preds = loaded_pipeline.predict(sample_data)
probs = loaded_pipeline.predict_proba(sample_data)[:, 1]
print(preds, probs)

